spring:
  application:
    name: NovaBankKotlin
  datasource:
    url: jdbc:postgresql://localhost:5432/novabank
    username: novabank
    password: novabank
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
novabank:
  kafka:
    topics:
      transfer-requested: bank.transfers.requested
      transfer-requested-dlt: bank.transfers.requested.dlt
